version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"  # Доступ к Flask через локальный порт 5000
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # Доступ к MongoDB извне (опционально)
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: