services:
  # Сервис для Flask приложения
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - mongo-db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app:Z
    networks:
      - app-network

  # Сервис для MongoDB
  mongo-db:
    image: mongo:8.0.9
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
