version: '3.8'

services:
  mongodb:
    image: mongo:6.0  # Фиксируем версию, чтобы избежать неожиданных обновлений
    container_name: mongodb
    restart: always
    env_file:
      - .env  # Переменные теперь загружаются из .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}  # Используем переменную из .env

  flask_app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    depends_on:
      - mongodb
    env_file:
      - .env
