version: '3'
services:
    mongo:
        image: mongo:5.0
        container_name: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    app:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./data:/data
        depends_on:
            - mongo

volumes:
    mongo_data:
